platform :ios, '8.0'

target 'MRSwiftExample' do

  use_frameworks!

  pod 'MRSwift', :path => '../'

  target 'MRSwiftExampleTests' do
    inherit! :search_paths
  end

  target 'MRSwiftExampleUITests' do
    inherit! :search_paths
  end

end
