platform :ios, '13.0'

target 'MRSwiftExample' do

  use_frameworks!

  pod 'MRSwift', :path => '../'

  target 'MRSwiftExampleTests' do
    inherit! :search_paths
  end

  target 'MRSwiftExampleUITests' do
    inherit! :search_paths
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5'
        end
    end
end
